import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  cellPin: {
    borderRadius: 10,
    width: 40,
    borderColor: '#958E8E',
    borderWidth: 1,
  },
  cellPinFilled: {
    borderRadius: 10,
    width: 40,
    borderColor: '#6379F4',
    borderWidth: 1,
  },
  header: {
    height: 100,
    backgroundColor: '#6379F4',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    flexDirection: 'column',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    padding: 10,
  },
  bar: {
    marginTop: 20,
    paddingLeft: 10,
    flexDirection: 'row',
    alignSelf: 'flex-start',
    marginBottom: 20,
    alignItems: 'center',
  },
  tabTitle: {
    color: 'white',
    marginLeft: 20,
    fontSize: 20,
  },
  subTitle: {
    textAlign: 'center',
    fontSize: 17,
    color: '#7A7886',
    marginBottom: 20,
  },
  formPin: {
    marginTop: 10,
    alignItems: 'center',
    marginBottom: 20,
  },
  round: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
    width: 80,
    height: 80,
    backgroundColor: '#1EC15F',
    borderRadius: 80,
    marginBottom: 20,
  },
  successText: {
    textAlign: 'center',
    fontSize: 14,
    color: '#88888F',
    marginTop: 20,
  },
  loginBtn: {
    width: '90%',
    backgroundColor: '#DADADA',
    padding: 18,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 190,
    borderRadius: 12,
  },
  loginBtnActive: {
    width: '90%',
    backgroundColor: '#6379F4',
    padding: 18,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 190,
    borderRadius: 12,
  },
  loginBtnContinue: {
    width: '90%',
    backgroundColor: '#DADADA',
    padding: 18,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 230,
    borderRadius: 12,
  },
  loginBtnActiveContinue: {
    width: '90%',
    backgroundColor: '#6379F4',
    padding: 18,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 230,
    borderRadius: 12,
  },
  loginText: {
    fontWeight: 'bold',
    color: '#88888F',
    fontSize: 20,
  },
  loginTextActive: {
    fontWeight: 'bold',
    color: 'white',
    fontSize: 20,
  },
});
